const shellEscape = (p: string) => p.replace(/"/g, '\\"');

// Generates shell script that logs session start event with timestamp and cast ID
export function renderSessionStartScript(args: { logPathAbs: string }): string {
  const { logPathAbs } = args;
  return `#!/bin/sh
# Auto-generated by Grimoire HookMaterializer. Do not edit — overwritten on every plugin load.
set -e
[ -z "$CAST_ID" ] && exit 0
TS=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")
LOG="${shellEscape(logPathAbs)}"
printf '{"stage":"in-progress","ts":"%s","castId":"%s"}\\n' "$TS" "$CAST_ID" >> "$LOG"
`;
}

// Generates shell script that captures file paths from tool execution events for later processing
export function renderPostToolUseScript(args: { scratchDirAbs: string }): string {
  const { scratchDirAbs } = args;
  return `#!/bin/sh
# Auto-generated by Grimoire HookMaterializer. Do not edit — overwritten on every plugin load.
set -e
[ -z "$CAST_ID" ] && exit 0
SCRATCH_DIR="${shellEscape(scratchDirAbs)}"
mkdir -p "$SCRATCH_DIR"
SCRATCH="$SCRATCH_DIR/$CAST_ID.paths"
FILE_PATH=$(python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("tool_input",{}).get("file_path",""))' 2>/dev/null || true)
if [ -n "$FILE_PATH" ]; then
  printf '%s\\n' "$FILE_PATH" >> "$SCRATCH"
fi
exit 0
`;
}

// Generates shell script that logs session end with deduplicated affected files collected during execution
export function renderStopScript(args: { logPathAbs: string; scratchDirAbs: string }): string {
  const { logPathAbs, scratchDirAbs } = args;
  return `#!/bin/sh
# Auto-generated by Grimoire HookMaterializer. Do not edit — overwritten on every plugin load.
set -e
[ -z "$CAST_ID" ] && exit 0
LOG="${shellEscape(logPathAbs)}"
SCRATCH_DIR="${shellEscape(scratchDirAbs)}"
SCRATCH="$SCRATCH_DIR/$CAST_ID.paths"
TS=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")
if [ -f "$SCRATCH" ]; then
  PATHS_JSON=$(sort -u "$SCRATCH" | python3 -c 'import sys,json; print(json.dumps([l.rstrip("\\n") for l in sys.stdin if l.strip()]))' 2>/dev/null || printf '%s' '[]')
  rm -f "$SCRATCH"
else
  PATHS_JSON="[]"
fi
printf '{"stage":"done","ts":"%s","castId":"%s","affectedFiles":%s}\\n' "$TS" "$CAST_ID" "$PATHS_JSON" >> "$LOG"
`;
}

