import { Vault } from 'obsidian';

/**
 * Minimal interface required by callers that only invoke `seed()`.
 * Allows plain objects to satisfy the type without a double-cast.
 * `CustomRefineSeeder` satisfies this interface structurally.
 */
export interface RefineSeeder {
  /** Creates a new custom Refine spell note and returns its vault-relative path. */
  seed(baseName?: string): Promise<string>;
}

/** Dependencies injected into CustomRefineSeeder. */
export interface CustomRefineSeederDeps {
  vault: Vault;
  /** Returns the vault-relative path of the forge output folder (e.g. "Spells/"). */
  forgeOutputFolder: () => string;
  /** Returns the full Refine system-prompt body including any materializer envelope. */
  renderBody: () => string;
}

/**
 * Creates a new custom Refine spell note in the forge output folder.
 * Content is the bundled Refine system prompt with a sentinel frontmatter header.
 * Uses a collision-suffix strategy ("Custom Refine", "Custom Refine 1", …) to avoid
 * overwriting an existing file.
 */
export class CustomRefineSeeder {
  readonly #deps: CustomRefineSeederDeps;

  constructor(deps: CustomRefineSeederDeps) {
    this.#deps = deps;
  }

  /**
   * Seeds a new custom Refine spell note and returns its vault-relative path.
   *
   * @param baseName - Base file name without extension (default: "Custom Refine")
   * @throws Error if no free file name is found within SAFETY_CAP attempts
   */
  async seed(baseName = 'Custom Refine'): Promise<string> {
    const folder = this.#deps.forgeOutputFolder().replace(/\/$/, '');
    const body = stripMaterializerEnvelope(this.#deps.renderBody());
    const content = `---\nsentinel: refine\n---\n\n%%\nAuto-generated by Grimoire (Create from default). Edit freely — the plugin does not overwrite this file.\n%%\n\n${body}`;

    // Find a free name using collision-suffix strategy
    let candidate = `${folder}/${baseName}.md`;
    let suffix = 1;
    const SAFETY_CAP = 100;
    while (this.#deps.vault.getAbstractFileByPath(candidate) !== null) {
      if (suffix > SAFETY_CAP) {
        throw new Error(`Could not find a free name after ${SAFETY_CAP} attempts`);
      }
      candidate = `${folder}/${baseName} ${suffix}.md`;
      suffix++;
    }

    await this.#deps.vault.create(candidate, content);
    return candidate;
  }
}

/**
 * Strips the leading RefineMaterializer envelope comment if present.
 * The materializer wraps generated content in a %% ... %% comment block;
 * user-editable copies should not include that automation marker.
 */
function stripMaterializerEnvelope(body: string): string {
  const prefix = '%%\nAuto-generated by Grimoire RefineMaterializer. Do not edit — overwritten on every plugin load and settings save.\n%%\n\n';
  if (body.startsWith(prefix)) {
    return body.slice(prefix.length);
  }
  return body;
}
