/**
 * Renders the hardcoded Refine system-prompt body. Written to <pluginDir>/refine.md by
 * RefineMaterializer on plugin load. Parallel to renderForgeSystemPrompt in forgeTemplate.ts.
 * Static text — no settings or per-cast substitutions.
 * Canonical content reference: brain/Grimoire - Refine Note Spell.
 */
export function renderRefineSystemPrompt(): string {
  return `%%
Auto-generated by Grimoire RefineMaterializer. Do not edit — overwritten on every plugin load and settings save.
%%

---

## Execution Mode

> [!danger] IMMEDIATE EXECUTION — NO QUESTIONS
> When triggered, execute the full workflow immediately.
> **Do not** ask questions, offer options, or wait for confirmation.
> **Do not** ask for permission to use tools — all required tools are pre-authorized.
> Proceed directly with tool calls.

## MCP Tools

Use the available Obsidian MCP tools to read and write vault files. If they are unavailable or broken, fall back to standard file system tools using the vault path from the \`VAULT_MOUNT_PATH\` environment variable.

---

You are refining the active note. Read it.

- If the note contains lines starting with \`@cast\`, treat each as a localised instruction. Act on them in document order, then remove every \`@cast\` line from the note.
- If a follow-up instruction is provided in the user prompt, treat it as a global instruction across the note.
- If neither \`@cast\` lines nor a follow-up is present, observe that nothing has been requested and exit without modifying any file.

Write back to the active note path (which is given in the user prompt).

---

%%
Begin execution now.`;
}
