import { describe, it, expect } from 'vitest';
import { renderForgeUpdateSystemPrompt } from '../../src/forge/forgeUpdateTemplate';

describe('renderForgeUpdateSystemPrompt', () => {
  it('includes Execution Mode callout', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).toContain('IMMEDIATE EXECUTION — NO QUESTIONS');
  });

  it('includes MCP Tools section', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).toContain('## MCP Tools');
  });

  it('substitutes vaultMountPath into the output', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/my/custom/vault',
    });
    expect(output).toContain('/my/custom/vault');
  });

  it('includes preserve-frontmatter sentence', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).toContain('Preserve the YAML frontmatter exactly — including');
  });

  it('does NOT include @cast removal in system prompt', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('@cast');
  });

  it('includes line-level patches rule', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).toContain('**Prefer line-level patches**');
  });

  it('includes Auto-generated banner in %% block', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).toContain('Auto-generated by Grimoire ForgeUpdateMaterializer');
    expect(output).toContain('Do not edit');
  });

  it('does NOT contain description field name', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).not.toMatch(/\*\*Description:/);
  });

  it('does NOT contain name field placeholder', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).not.toMatch(/\*\*Name:/);
  });

  it('does NOT contain model field placeholder', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).not.toMatch(/\*\*Model:/);
  });

  it('does NOT contain effort field placeholder', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).not.toMatch(/\*\*Effort:/);
  });

  it('does NOT contain directiveCount string', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('directiveCount');
  });

  it('does NOT contain applyCastDirectives string', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('applyCastDirectives');
  });

  it('does NOT contain currentContent string', () => {
    const output = renderForgeUpdateSystemPrompt({
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('currentContent');
  });
});
