import { describe, it, expect } from 'vitest';
import { renderForgeSystemPrompt } from '../../src/forge/forgeTemplate';

describe('renderForgeSystemPrompt', () => {
  it('includes Execution Mode callout', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('IMMEDIATE EXECUTION — NO QUESTIONS');
  });

  it('includes MCP Tools section', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('## MCP Tools');
  });

  it('substitutes vaultMountPath into the output', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/my/custom/vault',
    });
    expect(output).toContain('/my/custom/vault');
  });

  it('substitutes spellTag into the output', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'my-custom-tag',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('my-custom-tag');
  });

  it('substitutes forgeOutputFolder into the output', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'MyCustomFolder/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('MyCustomFolder/');
  });

  it('includes Auto-generated banner in %% block', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('Auto-generated by Grimoire ForgeMaterializer');
    expect(output).toContain('Do not edit');
  });

  it('does NOT contain description string', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toMatch(/\*\*Description:/);
  });

  it('does NOT contain name placeholder', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toMatch(/\*\*Name \(already sanitised\):/);
  });

  it('does NOT contain model placeholder', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('- **Model:');
  });

  it('does NOT contain effort placeholder', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('- **Effort:');
  });

  it('does NOT contain executeOnNote placeholder', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('executeOnNote');
    expect(output).not.toContain('grimoire-execute-on-note');
  });
});
