import { describe, it, expect } from 'vitest';
import { renderForgeSystemPrompt } from '../../src/forge/forgeTemplate';

describe('renderForgeSystemPrompt', () => {
  it('includes Execution Mode callout', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('IMMEDIATE EXECUTION — NO QUESTIONS');
  });

  it('includes MCP Tools section', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('## MCP Tools');
  });

  it('substitutes vaultMountPath into the output', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/my/custom/vault',
    });
    expect(output).toContain('/my/custom/vault');
  });

  it('substitutes spellTag into the output', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'my-custom-tag',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('my-custom-tag');
  });

  it('substitutes forgeOutputFolder into the output', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'MyCustomFolder/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('MyCustomFolder/');
  });

  it('includes Auto-generated banner in %% block', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('Auto-generated by Grimoire ForgeMaterializer');
    expect(output).toContain('Do not edit');
  });

  it('does NOT contain description string', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toMatch(/\*\*Description:/);
  });

  it('does NOT contain name placeholder', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toMatch(/\*\*Name \(already sanitised\):/);
  });

  it('does NOT contain model placeholder', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('- **Model:');
  });

  it('does NOT contain effort placeholder', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('- **Effort:');
  });

  it('does NOT contain unfilled placeholder variables', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('- **Description:');
    expect(output).not.toContain('- **Model:');
    expect(output).not.toContain('- **Effort:');
  });

  it('does not contain server-specific tool names', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).not.toContain('mcp__obsidian-mcp-tools__');
    expect(output).not.toContain('mcp__obsidian__');
    expect(output).not.toContain('search_vault_smart');
    expect(output).not.toContain('search_vault_simple');
    expect(output).not.toContain('get_vault_file');
    expect(output).not.toContain('create_vault_file');
  });

  it('explicitly states capability/intent-binding standard', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('by capability');
    expect(output).toContain('never by');
  });

  it('step 3 includes instruction to set grimoire-casting frontmatter', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('grimoire-casting');
    expect(output).toContain('provider: claude-code');
    expect(output).toContain('model');
  });

  it('step 3 still contains tags and grimoire-execute-on-note instructions', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('tags');
    expect(output).toContain('grimoire-execute-on-note');
  });

  it('footer contains Begin execution now', () => {
    const output = renderForgeSystemPrompt({
      spellTag: 'grimoire/spell',
      forgeOutputFolder: 'Spells/',
      vaultMountPath: '/vault',
    });
    expect(output).toContain('Begin execution now.');
  });
});
