import { describe, it, expect, vi, beforeEach } from 'vitest';
import { CustomRefineSeeder } from '../../src/refine/CustomRefineSeeder';

/** Builds a minimal Vault mock sufficient for CustomRefineSeeder. */
function makeVaultMock() {
  return {
    getAbstractFileByPath: vi.fn<(path: string) => object | null>().mockReturnValue(null),
    create: vi.fn<(path: string, content: string) => Promise<void>>().mockResolvedValue(undefined),
  };
}

const MATERIALIZER_ENVELOPE =
  '%%\nAuto-generated by Grimoire RefineMaterializer. Do not edit — overwritten on every plugin load and settings save.\n%%\n\n';

describe('CustomRefineSeeder', () => {
  let vault: ReturnType<typeof makeVaultMock>;
  let seeder: CustomRefineSeeder;

  beforeEach(() => {
    vault = makeVaultMock();
    seeder = new CustomRefineSeeder({
      vault: vault as any,
      forgeOutputFolder: () => 'Spells/',
      renderBody: () => `${MATERIALIZER_ENVELOPE}## Body content here`,
    });
  });

  // ------------------------------------------------------------------ (1)
  it('calls vault.create with path ending in "Custom Refine.md" by default', async () => {
    await seeder.seed();
    expect(vault.create).toHaveBeenCalledOnce();
    const [path] = vault.create.mock.calls[0];
    expect(path).toMatch(/Custom Refine\.md$/);
  });

  // ------------------------------------------------------------------ (2)
  it('content starts with sentinel frontmatter envelope', async () => {
    await seeder.seed();
    const [, content] = vault.create.mock.calls[0];
    expect(content).toMatch(/^---\nsentinel: refine\n---\n\n/);
  });

  // ------------------------------------------------------------------ (3)
  it('strips the RefineMaterializer envelope from the body', async () => {
    await seeder.seed();
    const [, content] = vault.create.mock.calls[0];
    // The materializer envelope header should NOT appear in the written content
    expect(content).not.toContain('Auto-generated by Grimoire RefineMaterializer');
    // The body text after the envelope should be present
    expect(content).toContain('## Body content here');
  });

  // ------------------------------------------------------------------ (4)
  it('appends collision-suffix when "Custom Refine.md" already exists', async () => {
    vault.getAbstractFileByPath.mockImplementation((path: string) => {
      if (path.endsWith('Custom Refine.md')) return { path }; // file exists
      return null;
    });

    await seeder.seed();

    const [path] = vault.create.mock.calls[0];
    expect(path).toMatch(/Custom Refine 1\.md$/);
  });

  // ------------------------------------------------------------------ (4b)
  it('increments suffix past 1 when both Custom Refine.md and Custom Refine 1.md exist', async () => {
    vault.getAbstractFileByPath.mockImplementation((path: string) => {
      if (path.endsWith('Custom Refine.md') || path.endsWith('Custom Refine 1.md')) {
        return { path };
      }
      return null;
    });

    await seeder.seed();

    const [path] = vault.create.mock.calls[0];
    expect(path).toMatch(/Custom Refine 2\.md$/);
  });

  // ------------------------------------------------------------------ (5)
  it('throws after 100 attempts when all candidates are taken', async () => {
    vault.getAbstractFileByPath.mockReturnValue({ path: 'exists' }); // always exists

    await expect(seeder.seed()).rejects.toThrow(/Could not find a free name after 100 attempts/);
    expect(vault.create).not.toHaveBeenCalled();
  });

  // ------------------------------------------------------------------ bonus: custom baseName
  it('accepts a custom baseName parameter', async () => {
    await seeder.seed('My Spell');
    const [path] = vault.create.mock.calls[0];
    expect(path).toMatch(/My Spell\.md$/);
  });

  // ------------------------------------------------------------------ bonus: folder trailing slash stripped
  it('strips trailing slash from forgeOutputFolder when building path', async () => {
    const seederWithSlash = new CustomRefineSeeder({
      vault: vault as any,
      forgeOutputFolder: () => 'Spells/',
      renderBody: () => '## body',
    });
    await seederWithSlash.seed();
    const [path] = vault.create.mock.calls[0];
    // Should NOT have double-slash (Spells//Custom Refine.md)
    expect(path).not.toContain('//');
    expect(path).toMatch(/^Spells\/Custom Refine\.md$/);
  });
});
