export interface ForgeSystemPromptInput {
  readonly spellTag: string;
  readonly forgeOutputFolder: string;
  readonly vaultMountPath: string;
}

/** Renders the forge system-prompt file content from per-settings inputs. Pure function; no I/O. */
export function renderForgeSystemPrompt(input: ForgeSystemPromptInput): string {
  const { spellTag, forgeOutputFolder, vaultMountPath } = input;

  return `%%
Auto-generated by Grimoire ForgeMaterializer. Do not edit — overwritten on every plugin load and settings save.
%%

---

## Execution Mode

> [!danger] IMMEDIATE EXECUTION — NO QUESTIONS
> When triggered, execute the full workflow immediately.
> **Do not** ask questions, offer options, or wait for confirmation.
> **Do not** ask for permission to use tools — all required tools are pre-authorized.
> Proceed directly with tool calls.

## MCP Tools

Use the available Obsidian MCP tools to read and write vault files. If they are unavailable or broken, fall back to standard file system tools using the vault path from the \`VAULT_MOUNT_PATH\` environment variable (${vaultMountPath}).

---

You are forging a new spell. A spell is a system prompt for Claude Code, stored as a Markdown note in the vault.

Forge inputs are provided in the user prompt.

Then execute in order:

1. Generate a complete, actionable spell body that fulfils the description. Write it as a clear Claude Code system prompt in imperative style.

2. Wrap the spell body in the standard Spell Wrapper structure — the same \`%%\` block format as this file:
   - Opening \`%%\` block containing: \`## Execution Mode\` (with the IMMEDIATE EXECUTION — NO QUESTIONS danger callout), and \`## MCP Tools\` (prefer Obsidian MCP, fall back to VAULT_MOUNT_PATH filesystem)
   - A \`---\` separator
   - The spell body
   - A \`---\` separator
   - Closing \`%%\` block containing only \`Begin execution now.\`

3. Set the file's YAML frontmatter \`tags\` field to \`[${spellTag}]\` and configure the execution metadata based on the user prompt.

4. Determine the output path: \`${forgeOutputFolder}\` followed by the spell name and \`.md\`. Create the folder if it does not exist.

5. Write the file. Use Obsidian MCP write tools if available, otherwise write via the filesystem path under VAULT_MOUNT_PATH. If the path already exists, try appending \`-2\`, then \`-3\`, and so on until a free name is found.

---

%%
Begin execution now.`;
}
