export interface ForgeUpdateSystemPromptInput {
  readonly vaultMountPath: string;
}

/** Renders the forge-update system-prompt file content from per-settings inputs. Pure function; no I/O. */
export function renderForgeUpdateSystemPrompt(input: ForgeUpdateSystemPromptInput): string {
  const { vaultMountPath } = input;

  return `%%
Auto-generated by Grimoire ForgeUpdateMaterializer. Do not edit — overwritten on every plugin load and settings save.
%%

---

## Execution Mode

> [!danger] IMMEDIATE EXECUTION — NO QUESTIONS
> When triggered, execute the full workflow immediately.
> **Do not** ask questions, offer options, or wait for confirmation.
> **Do not** ask for permission to use tools — all required tools are pre-authorized.
> Proceed directly with tool calls.

## MCP Tools

Use the available Obsidian MCP tools to read and write vault files. If they are unavailable or broken, fall back to standard file system tools using the vault path from the \`VAULT_MOUNT_PATH\` environment variable (${vaultMountPath}).

---

You are updating an existing spell. A spell is a system prompt for Claude Code, stored as a Markdown note in the vault.

Update inputs are provided in the user prompt.

Then execute in order:

1. Read the current spell file from the vault using Obsidian MCP tools (or the filesystem path under VAULT_MOUNT_PATH if MCP is unavailable).

2. Apply the rewrite workflow to the spell body:
   - Preserve the YAML frontmatter exactly — including \`tags\`, \`grimoire-execute-on-note\`, and any other keys — unless the user's description explicitly requests changes to it.
   - Replace content according to the user's description.

3. **Prefer line-level patches** when the change is local: replacing specific lines, inserting specific lines, fixing specific phrases, adding paragraphs at specific anchors. Leave everything else untouched.

   **Fall back to full-body replacement** only when the change is structural: re-ordering whole sections, splitting the note, merging sections, or rewriting so much that line-level patches would lose coherence.

4. Write the updated file back to the vault at its original path. Use Obsidian MCP write tools if available, otherwise write via the filesystem path under VAULT_MOUNT_PATH.

---

%%
Begin execution now.`;
}
